// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDudRb2dxe9NsrthYlpM7yEmB25AhhbHuY',
    appId: '1:552220718106:web:465928c1d0d2b7550d8da3',
    messagingSenderId: '552220718106',
    projectId: 'pristaapp-32731',
    authDomain: 'pristaapp-32731.firebaseapp.com',
    storageBucket: 'pristaapp-32731.appspot.com',
    measurementId: 'G-NB0BVZ1YH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJxrAD4KisFuzaYyT2-SQI5JmEHGY5cBk',
    appId: '1:552220718106:android:3ab9c7945e8665fa0d8da3',
    messagingSenderId: '552220718106',
    projectId: 'pristaapp-32731',
    storageBucket: 'pristaapp-32731.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnxBVbWZPewx8Aum-yXkjE8r3xMh7f4eA',
    appId: '1:552220718106:ios:0f2d7a13bf6e78750d8da3',
    messagingSenderId: '552220718106',
    projectId: 'pristaapp-32731',
    storageBucket: 'pristaapp-32731.appspot.com',
    iosBundleId: 'com.example.pristaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnxBVbWZPewx8Aum-yXkjE8r3xMh7f4eA',
    appId: '1:552220718106:ios:0f2d7a13bf6e78750d8da3',
    messagingSenderId: '552220718106',
    projectId: 'pristaapp-32731',
    storageBucket: 'pristaapp-32731.appspot.com',
    iosBundleId: 'com.example.pristaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDudRb2dxe9NsrthYlpM7yEmB25AhhbHuY',
    appId: '1:552220718106:web:b241b72340e71e740d8da3',
    messagingSenderId: '552220718106',
    projectId: 'pristaapp-32731',
    authDomain: 'pristaapp-32731.firebaseapp.com',
    storageBucket: 'pristaapp-32731.appspot.com',
    measurementId: 'G-DVNE76ZNRN',
  );
}
